In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array (10)
b = np.array ([1,2,3])
c = np.array ([[1,2,3], [4,5,6]])
d = np.array ([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [ ]:
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [ ]:
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)


In [ ]:
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
len(d)

2

In [ ]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [ ]:
np.eye(4,dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.zeros((2,4), dtype ='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((5,4), dtype ='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full((4,4),  6, dtype ='int')

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [ ]:
x = [30,2,50,23,17]
np.diag(x)

array([[30,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0, 50,  0,  0],
       [ 0,  0,  0, 23,  0],
       [ 0,  0,  0,  0, 17]])

In [ ]:
x = np.arange(1,15)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(14,)
1


In [ ]:
n = x.reshape(7,2)
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
(7, 2)
2


In [ ]:
y = n.ravel()
print(y.shape)
print(y)
print(y.ndim)

(14,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1


In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a = np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
print(a[5])

12


In [ ]:
a[3:9]

array([ 8, 10, 12, 14, 16, 18])

In [ ]:
print(a[::])
print(a[::-1])

[ 2  4  6  8 10 12 14 16 18 20]
[20 18 16 14 12 10  8  6  4  2]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a
print(a[1,1])
print(a[2,0])

5
7


In [ ]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b.shape
b


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
print(b[0][1][2])

6


In [ ]:
arr = np.arange(1,15)
print(arr)
print(arr[5:])
print(arr[1:7:2])
print(arr[:-6:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 6  7  8  9 10 11 12 13 14]
[2 4 6]
[14 13 12 11 10]


In [ ]:
print(a[2, 0:3])
print(a[0, 0:2])
print(a[1:3, 1:3])

[7 8 9]
[1 2]
[[5 6]
 [8 9]]


In [ ]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x2 = x1
print(x1)
print(x2)
print(np.shares_memory(x1,x2))
print(id(x1))
print(id(x2))

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]
True
137392399203760
137392399203760


In [ ]:
x2[0] = 10

In [ ]:
x4 = np.copy(x1)
print(x1)
print(x4)


[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [ ]:
x4[-1] = 250
print(x1)
print(x4)
print(np.shares_memory(x1,x4))

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 250]
False


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(a > 3)
print(a[a > 6])

[[False False False]
 [ True  True  True]
 [ True  True  True]]
[7 8 9]


In [ ]:
a[(a > 3) & (a <=8)]

array([4, 5, 6, 7, 8])

In [ ]:
x1 == x4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [ ]:
print(a.transpose())
print("----------")
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(x1)
print(x4)
np.vstack((x1,x4))

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 250]


array([[ 10,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,   1,   2,   3,   4,   5,   6,   7,   8, 250]])

In [ ]:
np.hstack((x1,x4))

array([ 10,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   1,   2,
         3,   4,   5,   6,   7,   8, 250])

In [ ]:
print(x1)
print(x4)
np.insert(x1, 7 ,x4)

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 250]


array([ 10,   1,   2,   3,   4,   5,   6,  10,   1,   2,   3,   4,   5,
         6,   7,   8, 250,   7,   8,   9])

In [ ]:
a = np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
np.insert(a, 5, [30,79,56])

array([ 1,  2,  3,  4,  5, 30, 79, 56,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16])

In [ ]:
print(x2)
np.delete(x2,8)


[10  1  2  3  4  5  6  7  8  9]


array([10,  1,  2,  3,  4,  5,  6,  7,  9])

In [ ]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(np.sin(a))
print(np.tan(2))
print(np.cos(3))

[[[ 0.84147098  0.90929743  0.14112001]
  [-0.7568025  -0.95892427 -0.2794155 ]
  [ 0.6569866   0.98935825  0.41211849]]]
-2.185039863261519
-0.9899924966004454


In [ ]:
print((np.sin(a))/(np.tan(a)))

[[[ 0.54030231 -0.41614684 -0.9899925 ]
  [-0.65364362  0.28366219  0.96017029]
  [ 0.75390225 -0.14550003 -0.91113026]]]


In [ ]:
np.exp(a)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]]])

In [ ]:
np.sum(a)

np.int64(45)

In [ ]:
np.sum(a,axis=2)

array([[ 6, 15, 24]])

In [ ]:
print(np.median(a))
print(np.mean(a))
print(np.std(a))
print(np.max(a))
print(np.sort(a))

5.0
5.0
2.581988897471611
9
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
arr = np.array([[12,14,16,17,19,20,22,24]])
print(arr)
arr1 = np.where(arr > 14)
print(arr1)

[[12 14 16 17 19 20 22 24]]
(array([0, 0, 0, 0, 0, 0]), array([2, 3, 4, 5, 6, 7]))


In [ ]:
print(dir(list))
print(dir(set))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', 

In [ ]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35
